---
commitizen:
  changelog_file: CHANGELOG.md
  changelog_incremental: true
  message:
    body: \n\n{body}
    breaking: '\n\nBREAKING CHANGE: {breaking}'
    footer: \n\n{footer}
    scope: ({scope})
    subject: ': {subject}'
    type: '{type}'
  name: cz_conventional_commits
  questions:
  - choices:
    - name: 'feat:     A new feature'
      value: feat
    - name: 'fix:      A bug fix'
      value: fix
    - name: 'docs:     Documentation only changes'
      value: docs
    - name: 'style:    Changes that do not affect the meaning of the code (white-space,
        formatting, missing semi-colons, etc)'
      value: style
    - name: 'refactor: A code change that neither fixes a bug nor adds a feature'
      value: refactor
    - name: 'perf:     A code change that improves performance'
      value: perf
    - name: 'test:     Adding missing tests or correcting existing tests'
      value: test
    - name: 'build:    Changes that affect the build system or external dependencies
        (example scopes: gulp, broccoli, npm)'
      value: build
    - name: 'ci:       Changes to our CI configuration files and scripts (example
        scopes: Travis, Circle, BrowserStack, SauceLabs)'
      value: ci
    - name: 'chore:    Other changes that don''t modify src or test files'
      value: chore
    - name: 'revert:   Reverts a previous commit'
      value: revert
    message: 'Select the type of change that you''re committing:'
    name: type
    type: list
  - message: 'What is the scope of this change (e.g. component or file name):'
    name: scope
    type: input
  - message: 'Write a short, imperative tense description of the change:'
    name: subject
    type: input
  - message: 'Provide a longer description of the change (optional). Use ''|'' to
      break new line:'
    name: body
    type: input
  - message: 'List any breaking changes (optional):'
    name: breaking
    type: input
  - message: 'Issues this commit closes (optional). E.g.: #31, #34:'
    name: footer
    type: input
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.1.0
